/*
 * Copyright 2026 Kazimierz Pogoda / Xemantic
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.xemantic.kotlin.data.api.test

import com.xemantic.kotlin.test.assert
import com.xemantic.kotlin.test.be
import com.xemantic.kotlin.test.have
import com.xemantic.kotlin.test.should
import kotlinx.serialization.json.Json
import kotlin.test.Test

/**
 * The `Foo { … }` DSL is a function named after the class, not an `invoke` operator on its
 * companion: a top-level function beside a top-level class, and a function in the enclosing type's
 * companion for a nested one. The annotated class therefore needs no companion of its own, which is
 * what lets it be `@Serializable` with no boilerplate — a companion generated by a plugin can be
 * extended by no other plugin, and two plugins generating one for the same class fails the
 * compilation outright.
 */
class DataApiFactoryTest {

    @Test
    fun `should build a class declaring its own companion object`() {
        // when
        val temperature = Temperature { celsius = 21.5 }

        // then
        assert(temperature.celsius == 21.5)
        // and the user's own companion member is untouched
        assert(Temperature.ABSOLUTE_ZERO == -273.15)
    }

    @Test
    fun `should build a Serializable class declaring no companion of its own`() {
        // when: the only companion `Point` has is the one kotlinx.serialization generates for
        // `serializer()` — the DSL entry point is a top-level `Point(block)` function beside it
        val point = Point {
            x = 1
            y = 2
        }

        // then
        point should {
            have(x == 1)
            have(y == 2)
        }
    }

    @Test
    fun `should serialize a DataApi class to JSON`() {
        // given
        val point = Point {
            x = 1
            y = 2
        }

        // when
        val json = Json.encodeToString(point)

        // then
        assert(json == """{"x":1,"y":2}""")
    }

    @Test
    fun `should deserialize a DataApi class from JSON`() {
        // given: deserialization drives the private primary constructor, which the generated
        // serializer reaches as a nested declaration of the very class it deserializes
        val json = """{"x":1,"y":2}"""

        // when
        val point = Json.decodeFromString<Point>(json)

        // then
        assert(point == Point { x = 1; y = 2 })
    }

    @Test
    fun `should copy a Serializable class through the builder DSL`() {
        // given
        val point = Point { x = 1; y = 2 }

        // when
        val moved = point.copy { x = 42 }

        // then
        moved should {
            have(x == 42)
            have(y == 2)
        }
    }

    @Test
    fun `should build a nested class through the enclosing type's factory`() {
        // when: `Payload.Base64` reads as if it were the constructor, but resolves to a function of
        // that name in `Payload`'s companion
        val payload: Payload = Payload.Base64 {
            mediaType = "image/png"
            data = "iVBORw0KGgo="
        }

        // then
        payload should {
            be<Payload.Base64>()
            have(mediaType == "image/png")
            have(data == "iVBORw0KGgo=")
        }
    }

    @Test
    fun `should copy and compare a nested class`() {
        // given
        val link = Payload.Url {
            mediaType = "text/html"
            url = "https://xemantic.com"
        }

        // when
        val titled = link.copy { title = "Xemantic" }

        // then
        titled should {
            have(url == "https://xemantic.com")
            have(title == "Xemantic")
        }
        assert(link == Payload.Url { mediaType = "text/html"; url = "https://xemantic.com" })
    }

    @Test
    fun `should serialize a nested class polymorphically`() {
        // given
        val payload: Payload = Payload.Url {
            mediaType = "text/html"
            url = "https://xemantic.com"
        }

        // when
        val json = Json.encodeToString(payload)

        // then
        assert(json == """{"type":"url","mediaType":"text/html","url":"https://xemantic.com"}""")
        assert(Json.decodeFromString<Payload>(json) == payload)
    }

    @Test
    fun `should build a class nested in an object`() {
        // when: an object cannot have a companion, so the factory is a member of the object itself
        val entry = Registry.Entry {
            key = "kotlin"
            value = "2.4.10"
        }

        // then
        entry should {
            have(key == "kotlin")
            have(value == "2.4.10")
        }
    }

    @Test
    fun `should build a class nested in a companion object`() {
        // when: a companion cannot have a companion either, so it hosts the factory directly —
        // alongside the factories of the classes nested in the class it is the companion of
        val sku = Catalog.Sku { code = "K-2410" }
        val item = Catalog.Item { name = "Kotlin" }

        // then
        assert(sku.code == "K-2410")
        assert(item.name == "Kotlin")
    }

    @Test
    fun `should build an internal class`() {
        // when
        val ticket = Ticket { id = "T-1" }

        // then
        assert(ticket.id == "T-1")
    }

    @Test
    fun `should build a class named after a generated member`() {
        // when: `copy` is both this class's name — and so its factory's — and the name of the member
        // generated into every `@DataApi` class
        val one = copy { x = 1 }

        // then
        assert(one.x == 1)
        assert(one.copy { x = 2 }.x == 2)
    }

}
