/*
 * Copyright 2025-2026 Kazimierz Pogoda / Xemantic
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.xemantic.kotlin.data.api.compiler.fir

import com.xemantic.kotlin.data.api.compiler.BUILDER_NAME
import com.xemantic.kotlin.data.api.compiler.DATA_API_ANNOTATION_FQ_NAME
import com.xemantic.kotlin.data.api.compiler.DATA_API_DSL_ANNOTATION_CLASS_ID
import com.xemantic.kotlin.data.api.compiler.DataApiPluginKey
import com.xemantic.kotlin.data.api.compiler.assignedFlagName
import org.jetbrains.kotlin.builtins.functions.FunctionTypeKind
import org.jetbrains.kotlin.descriptors.Visibilities
import org.jetbrains.kotlin.descriptors.Visibility
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.declarations.DirectDeclarationsAccess
import org.jetbrains.kotlin.fir.expressions.FirAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotation
import org.jetbrains.kotlin.fir.expressions.builder.buildAnnotationArgumentMapping
import org.jetbrains.kotlin.fir.extensions.FirDeclarationGenerationExtension
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.MemberGenerationContext
import org.jetbrains.kotlin.fir.extensions.NestedClassGenerationContext
import org.jetbrains.kotlin.fir.extensions.predicate.DeclarationPredicate
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.plugin.createCompanionObject
import org.jetbrains.kotlin.fir.plugin.createConeType
import org.jetbrains.kotlin.fir.plugin.createConstructor
import org.jetbrains.kotlin.fir.plugin.createDefaultPrivateConstructor
import org.jetbrains.kotlin.fir.plugin.createMemberFunction
import org.jetbrains.kotlin.fir.plugin.createMemberProperty
import org.jetbrains.kotlin.fir.plugin.createNestedClass
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirNamedFunctionSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirPropertySymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.types.ConeAttributes
import org.jetbrains.kotlin.fir.types.ConeKotlinType
import org.jetbrains.kotlin.fir.types.CompilerConeAttributes
import org.jetbrains.kotlin.fir.types.builder.buildResolvedTypeRef
import org.jetbrains.kotlin.fir.types.constructType
import org.jetbrains.kotlin.fir.types.isNullableAny
import org.jetbrains.kotlin.fir.types.typeContext
import org.jetbrains.kotlin.fir.types.withAttributes
import org.jetbrains.kotlin.fir.types.withNullability
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames

/**
 * Synthesizes, for every `@DataApi`-annotated class, a nested `Builder` and a companion object
 * with an `invoke` operator, e.g. for `Person`:
 *
 * ```
 * class Person {
 *     class Builder {
 *         var name: String? = null
 *         var age: Int? = null
 *         private var age$isAssigned: Boolean = false // only when `age` has a default value
 *         fun build(): Person = ...
 *     }
 *     fun copy(block: Builder.() -> Unit): Person =
 *         Builder().apply { name = this@Person.name; age = this@Person.age }.apply(block).build()
 *     companion object {
 *         operator fun invoke(block: Builder.() -> Unit): Person = Builder().apply(block).build()
 *     }
 * }
 * ```
 *
 * Only the declaration *shapes* are produced here (FIR); the bodies of `build` and `invoke` are
 * filled in by the IR backend (see `DataApiIrGenerationExtension`), which also takes over the
 * setters of defaulted properties to maintain their `$isAssigned` flags. The builder's mutable
 * `var`s and both constructors get their bodies generated by Fir2Ir automatically.
 */
class DataApiBuilderGenerator(
    session: FirSession
) : FirDeclarationGenerationExtension(session) {

    private companion object {
        val BUILD_NAME: Name = Name.identifier("build")
        val COPY_NAME: Name = Name.identifier("copy")
        val INVOKE_NAME: Name = Name.identifier("invoke")
        val BLOCK_NAME: Name = Name.identifier("block")
        val EQUALS_NAME: Name = Name.identifier("equals")
        val HASHCODE_NAME: Name = Name.identifier("hashCode")
        val TO_STRING_NAME: Name = Name.identifier("toString")
        val OTHER_NAME: Name = Name.identifier("other")
        val DATA_MEMBER_NAMES: Set<Name> = setOf(EQUALS_NAME, HASHCODE_NAME, TO_STRING_NAME)
        val COMPANION_NAME: Name = SpecialNames.DEFAULT_NAME_FOR_COMPANION_OBJECT
        val PREDICATE: DeclarationPredicate =
            DeclarationPredicate.create { annotated(DATA_API_ANNOTATION_FQ_NAME) }
    }

    /** Builder class id -> owning `@DataApi` class symbol. */
    private val builderOwners = mutableMapOf<ClassId, FirRegularClassSymbol>()

    /** Companion class id -> owning `@DataApi` class symbol. */
    private val companionOwners = mutableMapOf<ClassId, FirRegularClassSymbol>()

    /**
     * Whether [symbol] is a `@DataApi` class the plugin can generate for. A class the annotation
     * does not fit — see [dataApiViolation] — is left entirely untouched, so that the error
     * `DataApiCheckersExtension` reports on it is the only thing the user has to read, rather than
     * the fallout of half-generated declarations.
     */
    private fun isDataApiClass(symbol: FirClassSymbol<*>): Boolean =
        session.predicateBasedProvider.matches(PREDICATE, symbol) &&
            symbol.dataApiViolation() == null

    override fun getNestedClassifiersNames(
        classSymbol: FirClassSymbol<*>,
        context: NestedClassGenerationContext
    ): Set<Name> =
        if (isDataApiClass(classSymbol)) setOf(BUILDER_NAME, COMPANION_NAME)
        else emptySet()

    override fun generateNestedClassLikeDeclaration(
        owner: FirClassSymbol<*>,
        name: Name,
        context: NestedClassGenerationContext
    ): FirClassLikeSymbol<*>? {
        if (owner !is FirRegularClassSymbol || !isDataApiClass(owner)) return null
        return when (name) {
            BUILDER_NAME -> createNestedClass(owner, BUILDER_NAME, DataApiPluginKey)
                // confines the builder DSL block to its own receiver, so that in a nested block an
                // assignment that does not resolve here fails to compile instead of falling
                // through to the enclosing builder and mutating the outer object
                .apply { replaceAnnotations(listOf(dslMarkerAnnotation())) }
                .symbol
                .also { builderOwners[it.classId] = owner }
            COMPANION_NAME -> createCompanionObject(owner, DataApiPluginKey).symbol
                .also { companionOwners[it.classId] = owner }
            else -> null
        }
    }

    override fun getCallableNamesForClass(
        classSymbol: FirClassSymbol<*>,
        context: MemberGenerationContext
    ): Set<Name> = when (val classId = classSymbol.classId) {
        in builderOwners ->
            dataProperties(builderOwners.getValue(classId))
                .flatMapTo(mutableSetOf()) { property ->
                    if (property.hasDefault) listOf(property.name, assignedFlagName(property.name))
                    else listOf(property.name)
                }
                .apply { add(BUILD_NAME); add(SpecialNames.INIT) }
        in companionOwners -> setOf(INVOKE_NAME, SpecialNames.INIT)
        else -> if (isDataApiClass(classSymbol)) {
            (DATA_MEMBER_NAMES - userDeclaredDataMemberNames(classSymbol)) + COPY_NAME
        } else emptySet()
    }

    /**
     * The `equals`/`hashCode`/`toString` names already declared by the user on [classSymbol], which
     * the plugin must leave untouched instead of generating a clashing member (as the Kotlin
     * compiler does for `data` classes).
     *
     * Matched by full signature, not by name and arity: an unrelated typed overload such as
     * `fun equals(other: Money): Boolean` does not override `Any.equals`, so treating it as the
     * user's own `equals` would silently leave the class with identity equality.
     */
    @OptIn(DirectDeclarationsAccess::class)
    private fun userDeclaredDataMemberNames(classSymbol: FirClassSymbol<*>): Set<Name> =
        classSymbol.declarationSymbols
            .filterIsInstance<FirNamedFunctionSymbol>()
            .filterTo(mutableSetOf()) { function ->
                when (function.name) {
                    EQUALS_NAME -> function.valueParameterSymbols.singleOrNull()
                        ?.resolvedReturnType?.isNullableAny == true
                    HASHCODE_NAME, TO_STRING_NAME -> function.valueParameterSymbols.isEmpty()
                    else -> false
                }
            }
            .mapTo(mutableSetOf()) { it.name }

    override fun generateProperties(
        callableId: CallableId,
        context: MemberGenerationContext?
    ): List<FirPropertySymbol> {
        val owner = context?.owner ?: return emptyList()
        val dataOwner = builderOwners[owner.classId] ?: return emptyList()
        val name = callableId.callableName
        val properties = dataProperties(dataOwner)
        properties.firstOrNull { it.name == name }?.let { property ->
            return listOf(
                createMemberProperty(
                    owner = owner,
                    key = DataApiPluginKey,
                    name = property.name,
                    returnType = property.builderType,
                    isVal = false,
                    hasBackingField = true
                ) {
                    // a `private`/`internal` property must not become settable from anywhere
                    // through the builder
                    visibility = property.visibility
                }.symbol
            )
        }
        // the private `<property>$isAssigned` flag backing a defaulted property
        properties.firstOrNull { it.hasDefault && assignedFlagName(it.name) == name }
            ?: return emptyList()
        return listOf(
            createMemberProperty(
                owner = owner,
                key = DataApiPluginKey,
                name = name,
                returnType = session.builtinTypes.booleanType.coneType,
                isVal = false,
                hasBackingField = true
            ) {
                visibility = Visibilities.Private
            }.symbol
        )
    }

    override fun generateFunctions(
        callableId: CallableId,
        context: MemberGenerationContext?
    ): List<FirNamedFunctionSymbol> {
        val owner = context?.owner ?: return emptyList()
        val classId = owner.classId
        val name = callableId.callableName
        return when {
            classId in builderOwners && name == BUILD_NAME -> {
                val targetType = builderOwners.getValue(classId).targetType()
                listOf(
                    createMemberFunction(
                        owner, DataApiPluginKey, BUILD_NAME, targetType
                    ).symbol
                )
            }
            classId in companionOwners && name == INVOKE_NAME -> {
                val dataOwner = companionOwners.getValue(classId)
                val builderType = builderClassId(dataOwner).createConeType(session)
                val blockType = builderType.toExtensionFunctionType()
                listOf(
                    createMemberFunction(
                        owner, DataApiPluginKey, INVOKE_NAME, dataOwner.targetType()
                    ) {
                        status { isOperator = true }
                        valueParameter(BLOCK_NAME, blockType)
                    }.symbol
                )
            }
            isDataApiClass(owner) && name == COPY_NAME -> {
                val dataOwner = owner as FirRegularClassSymbol
                val builderType = builderClassId(dataOwner).createConeType(session)
                val blockType = builderType.toExtensionFunctionType()
                listOf(
                    createMemberFunction(
                        owner, DataApiPluginKey, COPY_NAME, dataOwner.targetType()
                    ) {
                        valueParameter(BLOCK_NAME, blockType)
                    }.symbol
                )
            }
            isDataApiClass(owner) && name == EQUALS_NAME -> listOf(
                createMemberFunction(
                    owner, DataApiPluginKey, EQUALS_NAME, session.builtinTypes.booleanType.coneType
                ) {
                    status { isOverride = true }
                    valueParameter(OTHER_NAME, session.builtinTypes.nullableAnyType.coneType)
                }.symbol
            )
            isDataApiClass(owner) && name == HASHCODE_NAME -> listOf(
                createMemberFunction(
                    owner, DataApiPluginKey, HASHCODE_NAME, session.builtinTypes.intType.coneType
                ) {
                    status { isOverride = true }
                }.symbol
            )
            isDataApiClass(owner) && name == TO_STRING_NAME -> listOf(
                createMemberFunction(
                    owner, DataApiPluginKey, TO_STRING_NAME, session.builtinTypes.stringType.coneType
                ) {
                    status { isOverride = true }
                }.symbol
            )
            else -> emptyList()
        }
    }

    override fun generateConstructors(
        context: MemberGenerationContext
    ): List<FirConstructorSymbol> {
        val classId = context.owner.classId
        return when (classId) {
            in builderOwners -> listOf(
                createConstructor(
                    context.owner,
                    DataApiPluginKey,
                    isPrimary = true,
                    generateDelegatedNoArgConstructorCall = true
                ).symbol
            )
            in companionOwners -> listOf(
                createDefaultPrivateConstructor(context.owner, DataApiPluginKey).symbol
            )
            else -> emptyList()
        }
    }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(PREDICATE)
    }

    private fun builderClassId(dataOwner: FirRegularClassSymbol): ClassId =
        dataOwner.classId.createNestedClassId(BUILDER_NAME)

    private fun FirRegularClassSymbol.targetType(): ConeKotlinType =
        constructType(emptyArray(), false, ConeAttributes.Empty)

    private fun ConeKotlinType.toExtensionFunctionType(): ConeKotlinType =
        FunctionTypeKind.Function.numberedClassId(1)
            .createConeType(
                session,
                arrayOf(this, session.builtinTypes.unitType.coneType)
            )
            .withAttributes(
                ConeAttributes.create(listOf(CompilerConeAttributes.ExtensionFunctionType))
            )

    @OptIn(DirectDeclarationsAccess::class)
    private fun dataProperties(owner: FirRegularClassSymbol): List<DataProperty> {
        val constructor = owner.declarationSymbols
            .filterIsInstance<FirConstructorSymbol>()
            .firstOrNull { it.isPrimary } ?: return emptyList()
        val visibilities = owner.declarationSymbols
            .filterIsInstance<FirPropertySymbol>()
            .associate { it.name to it.rawStatus.visibility }
        return constructor.valueParameterSymbols.map { parameter ->
            DataProperty(
                name = parameter.name,
                builderType = parameter.resolvedReturnType
                    .withNullability(true, session.typeContext),
                hasDefault = parameter.hasDefaultValue,
                visibility = visibilities[parameter.name].orPublic()
            )
        }
    }

    /** An undeclared visibility resolves to `public`, the Kotlin default. */
    private fun Visibility?.orPublic(): Visibility = when (this) {
        Visibilities.Private, Visibilities.Protected, Visibilities.Internal -> this
        else -> Visibilities.Public
    }

    private fun dslMarkerAnnotation(): FirAnnotation = buildAnnotation {
        annotationTypeRef = buildResolvedTypeRef {
            coneType = DATA_API_DSL_ANNOTATION_CLASS_ID.createConeType(session)
        }
        argumentMapping = buildAnnotationArgumentMapping()
    }

    private class DataProperty(
        val name: Name,
        val builderType: ConeKotlinType,
        val hasDefault: Boolean,
        val visibility: Visibility
    )

}
